Documentation/FrontendTesting.md
Documentation/testing/frontend/FrontendTesting.md
Documentation/testing/frontend/template.comonent.spec.ts
src/digitalIdentity-frontend/src/app/app.component.spec.ts
src/digitalIdentity-frontend/src/app/login-page/login-page.component.spec.ts
src/digitalIdentity-frontend/src/app/login-page/login-page.component.ts
src/digitalIdentity-frontend/src/app/register-page/register-page.component.spec.ts

- Created an introduction into testing within angular
- Created some example tests within the login-page.component.spec.ts
- Created a template for testing angular components
- Minor refactoring in login-page.component.ts

Frontend testing

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/AuthenticationController.java
src/digitalIdentity-frontend/src/app/app.module.ts
src/digitalIdentity-frontend/src/app/information-pop-up/information-pop-up.component.html
src/digitalIdentity-frontend/src/app/information-pop-up/information-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/information-pop-up/information-pop-up.component.ts
src/digitalIdentity-frontend/src/app/login-page/login-page.component.ts
src/digitalIdentity-frontend/src/app/material/material.module.ts

Login event implementation

---

Documentation/api/openapi_didentity.yaml
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/ConnectionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/model/User.java
src/digitalIdentity-backend/src/main/resources/application.properties

Finished #32 and updated API. Implementation fits API. 
@annikakrause

32 di overview backend

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/AuthenticationController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/ConnectionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/model/User.java
src/digitalIdentity-frontend/src/app/DI-Overview/DI-Overview.component.html
src/digitalIdentity-frontend/src/app/DI-Overview/DI-Overview.component.ts
src/digitalIdentity-frontend/src/app/app.module.ts
src/digitalIdentity-frontend/src/app/edit-window-pop-up/edit-window-pop-up.component.html
src/digitalIdentity-frontend/src/app/edit-window-pop-up/edit-window-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/edit-window-pop-up/edit-window-pop-up.component.ts
src/digitalIdentity-frontend/src/app/login-page/login-page.component.ts
src/digitalIdentity-frontend/src/app/register-page/register-page.component.html
src/digitalIdentity-frontend/src/app/register-page/register-page.component.ts

Completed https://github.com/amosproj/amos2022ss04-digital-identity/issues/66#
@annikakrause

Frontend edit pers info

---

src/digitalIdentity-backend/pom.xml
src/digitalIdentity-backend/src/main/java/didentity/QrGenerator/QrGenerator.java

@Jean28518 Am besten testest du im #9 E-Mail versenden, ob das Format etc. so passt. Sonst können wir es nochmal anpassen.

#47 qr code generator

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/ConnectionController.java
src/digitalIdentity-frontend/src/app/DI-Overview/DI-Overview.component.html
src/digitalIdentity-frontend/src/app/DI-Overview/DI-Overview.component.ts
src/digitalIdentity-frontend/src/app/edit-window-pop-up/edit-window-pop-up.component.ts

Done with #56, fixed json format error in backend, DI-Overview shows now data from the db and refreshes after editing them.
@annikakrause

#56  Frontend-Backend Connection: Overview page of digital identities

---

src/digitalIdentity-frontend/src/app/DI-Overview/DI-Overview.component.html
src/digitalIdentity-frontend/src/app/app-routing.module.ts
src/digitalIdentity-frontend/src/app/app.component.html
src/digitalIdentity-frontend/src/app/app.component.ts
src/digitalIdentity-frontend/src/app/app.module.ts
src/digitalIdentity-frontend/src/app/home/home.component.html
src/digitalIdentity-frontend/src/app/home/home.component.ts
src/digitalIdentity-frontend/src/app/navigation-bar/navigation-bar.component.css
src/digitalIdentity-frontend/src/app/navigation-bar/navigation-bar.component.html
src/digitalIdentity-frontend/src/app/navigation-bar/navigation-bar.component.spec.ts
src/digitalIdentity-frontend/src/app/navigation-bar/navigation-bar.component.ts
src/digitalIdentity-frontend/src/app/register-page/register-page.component.ts
src/digitalIdentity-frontend/src/app/schema-overview/schema-overview.component.html
src/digitalIdentity-frontend/src/app/schema-overview/schema-overview.component.spec.ts
src/digitalIdentity-frontend/src/app/schema-overview/schema-overview.component.ts

Signed-off-by: Steve <steve.pegouen@fau.de>

creation of the navigation bar

---

src/digitalIdentity-frontend/src/app/createDI-page/createDI-page.component.ts

Implements #101 completely.
Signed-off-by: Jean-Frédéric Vogelbacher <jean-frederic.vog.vogelbacher@fau.de>

Display error messages in registration process

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/model/User.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/DIConnectionService.java

Signed-off-by: Jean28518 <jean-frederic.vog.vogelbacher@fau.de>

Implement #110 (store invitationurl in database)

---

Documentation/api/openapi_didentity.yaml
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/ConnectionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/SchemaController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/messages/responses/SchemasResponse.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/LissiApiService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/SchemaService.java
src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.html
src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.ts

RM: @steve-237
Note: Neither the API is not adjusted nor tests are written. Nethertheless, someone can review it, as the code will not change at all/only by a bit :)

54 backend provide existing schemas

---

Documentation/api/openapi_didentity.yaml
src/digitalIdentity-backend/pom.xml
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/DIConnectionService.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/Services/DIConnectionServiceTest.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/repository/UserRepositoryTest.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/shared/samples/UserSamples.java
src/digitalIdentity-backend/src/test/resources/application.properties

Tests for DIConnectionService.create are done :) 
Part of #119

Test di connection service.create

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/StrongPasswordService.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/Services/DIConnectionServiceTest.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/Services/StrongPasswordServiceTest.java

added tests for password.
Should be reviewed after #147 and #146 got merged into main.

Test default password

---

src/digitalIdentity-frontend/package-lock.json
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.ts
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.ts

Fixed the bug #132 and added tests for the implemented changes.
RM: @Idontker

Bugfix case sensitive email #132

---

src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.html
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.ts
src/digitalIdentity-frontend/src/app/pages/error-page/error-page.component.spec.ts

Added tests for create DI page. 65.85% test coverage so far, can be improved (suggestions are commented), but should work for now.
RM: @Idontker

Tests for create DI component

---

Documentation/api/openapi_didentity.yaml
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/CredentialDefinitionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/SchemaController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/model/User.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/CredentialDefinitionService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/DIConnectionService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/HttpService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/LissiApiService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/SchemaService.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/controller/AuthenticationControllerTests.java
src/digitalIdentity-frontend/package-lock.json
src/digitalIdentity-frontend/src/app/app-routing.module.ts
src/digitalIdentity-frontend/src/app/app.component.css
src/digitalIdentity-frontend/src/app/app.module.ts
src/digitalIdentity-frontend/src/app/components/filtered-table/filtered-table.component.html
src/digitalIdentity-frontend/src/app/components/filtered-table/filtered-table.component.spec.ts
src/digitalIdentity-frontend/src/app/components/filtered-table/filtered-table.component.ts
src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.ts
src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.html
src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.ts
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.html
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.ts
src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.html

- added overview credential definition page including backend connection
- some minor refactoring in frontend and backend
- tests for filtered-table component
Release manager: @Idontker

Overview credentials

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/CredentialDefinitionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/CredentialDefinitionService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/LissiApiService.java

Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

added revocable parameter to credential definition #112

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/HttpService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/LissiApiService.java
src/digitalIdentity-frontend/package-lock.json
src/digitalIdentity-frontend/package.json
src/digitalIdentity-frontend/src/app/app.module.ts
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.html
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/add-dito-credential-pop-up/add-dito-credential-pop-up.component.html
src/digitalIdentity-frontend/src/app/shared/pop-up/add-dito-credential-pop-up/add-dito-credential-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/add-dito-credential-pop-up/add-dito-credential-pop-up.component.ts

Actual state of #114. Sorry for the delay. I'm still on it.

Created Pop-up to add DI to Credential

---

src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.ts

Frontend test schema overview

---

README.md
src/digitalIdentity-frontend/cypress.config.ts
src/digitalIdentity-frontend/cypress/e2e/diconnections.cy.ts
src/digitalIdentity-frontend/cypress/e2e/navigation.cy.ts
src/digitalIdentity-frontend/cypress/fixtures/example.json
src/digitalIdentity-frontend/cypress/support/commands.ts
src/digitalIdentity-frontend/cypress/support/e2e.ts
src/digitalIdentity-frontend/package-lock.json
src/digitalIdentity-frontend/package.json
src/digitalIdentity-frontend/src/app/app.component.html
src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.html
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.html

added e2e example test

---

src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.spec.ts

Signed-off-by: Jean28518 <jean-frederic.vog.vogelbacher@fau.de>

update test for hr employee checkbox

---

src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.html
src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.ts
src/digitalIdentity-frontend/src/app/shared/filtered-table/delete-dialog/delete-dialog.component.html
src/digitalIdentity-frontend/src/app/shared/filtered-table/filtered-table.component.ts

added alias to overview, 
added email/alias (whatever exists) to delete connection dialog

166 fixed delete di

---

src/digitalIdentity-frontend/src/app/pages/schema/create-schema-page/create-schema-page.component.html

Signed-off-by: Steve Pegouen <steve.pegouen@fau.de>

fixed problem

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/CredentialService.java
src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/services/CredentialServiceTest.java

Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

Added tests for CredentialService #114

---

src/digitalIdentity-frontend/src/app/components/cred-def-detail/cred-def-activities/cred-def-activities.component.ts
src/digitalIdentity-frontend/src/app/components/cred-def-detail/cred-def-detail-pop-up/cred-def-detail-pop-up.component.ts
src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.ts
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.ts
src/digitalIdentity-frontend/src/app/pages/credential/credential-overview-page/credDef-overview-page.component.ts
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.ts
src/digitalIdentity-frontend/src/app/pages/proofTemplate/proofTemplate-overview-page/proofTemplate-overview-page.component.ts
src/digitalIdentity-frontend/src/app/pages/schema/create-schema-page/create-schema-page.component.ts
src/digitalIdentity-frontend/src/app/pages/schema/schema-overview-page/schema-overview-page.component.ts
src/digitalIdentity-frontend/src/app/services/backend-http-service/backend-http-service.service.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/forgot-password-pop-up/forgot-password-pop-up.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.ts

Refactor frontend http service

---

src/digitalIdentity-frontend/src/app/components/cred-def-detail/cred-def-activities/cred-def-activities.component.spec.ts
src/digitalIdentity-frontend/src/app/components/cred-def-detail/cred-def-detail-pop-up/cred-def-detail-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.spec.ts
src/digitalIdentity-frontend/src/app/components/proof-detail/proof-activities/proof-activities.component.spec.ts
src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.spec.ts
src/digitalIdentity-frontend/src/app/services/backend-http-service/backend-http-service.service.spec.ts
src/digitalIdentity-frontend/src/app/shared/filtered-table/delete-dialog/delete-dialog.component.spec.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/add-di-to-proof-template-pop-up/add-di-to-proof-template-pop-up.component.spec.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/edit-window-pop-up/edit-window-pop-up.component.spec.ts

Signed-off-by: Annika Krause <annika.krause@fau.de>

fixed 22 failing tests

---

src/digitalIdentity-frontend/src/styles.scss

The font gets loaded on all computers now, even if it's not installed.
RM: @Jean28518

270 text font does not get loaded on all computers

---

src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.html

Improve handling of empty tabels
RM : @Jean28518

272 proof template addition information improve handling of empty tabels

---

src/digitalIdentity-frontend/src/app/pages/credential/create-credDef/create-cred-def.component.html
src/digitalIdentity-frontend/src/app/pages/schema/create-schema-page/create-schema-page.component.html
src/digitalIdentity-frontend/src/app/pages/schema/create-schema-page/create-schema-page.component.ts

Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

Disabled button #257

---

src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.ts
src/digitalIdentity-frontend/src/app/pages/credential/create-credDef/create-cred-def.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/add-di-to-proof-template-pop-up/add-di-to-proof-template-pop-up.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/add-dito-credential-pop-up/add-dito-credential-pop-up.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.css
src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.html
src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.ts

Pop up information windows according to mockup
RM : @Jean28518

267 pop up windows according to mockup

---

src/digitalIdentity-frontend/src/app/pages/home-page/home-page.component.css
src/digitalIdentity-frontend/src/app/pages/home-page/home-page.component.html

Reverts amosproj/amos2022ss04-digital-identity#285

Revert "265 landing page style"

---

src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/ConnectionController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/controller/CredentialController.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/messages/answers/proofs/PagedProofAnswer.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/messages/answers/proofs/ProofAnswer.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/model/connection/Connection.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/CredentialService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/DIConnectionService.java
src/digitalIdentity-backend/src/main/java/didentity/amos/digitalIdentity/services/LissiApiService.java
src/digitalIdentity-frontend/src/app/pages/DI/DIOverview-page/DIOverview-page.component.ts
src/digitalIdentity-frontend/src/app/services/data-update.service.spec.ts
src/digitalIdentity-frontend/src/app/services/data-update.service.ts
src/digitalIdentity-frontend/src/app/shared/filtered-table/filtered-table.component.ts

- Due to performance issues the open credentials and open proofs are loading a bit longer than the rest of the overview table (wait for some seconds ;)
- Lissi seems not to distinguish between canceled and pending proofs

171 overview of di values for open credentials open proofs connection status

---

src/digitalIdentity-frontend/src/app/pages/home-page/home-page.component.html

Due to Annis feedback I adjusted the home-page (#265)

265 adjust for smaller windows

---

src/digitalIdentity-frontend/src/app/pages/proof-templ/create-proof-template/create-proof-templ/cpt-step2/cpt-step2.component.html
src/digitalIdentity-frontend/src/app/pages/proof-templ/create-proof-template/create-proof-templ/cpt-step3/cpt-step3.component.html
src/digitalIdentity-frontend/src/app/pages/proof-templ/create-proof-template/create-proof-templ/cpt-step3b/cpt-step3b.component.html
src/digitalIdentity-frontend/src/app/pages/proof-templ/create-proof-template/create-proof-templ/cpt-step3b/cpt-step3b.component.ts
src/digitalIdentity-frontend/src/app/pages/proof-templ/create-proof-template/create-proof-templ/cpt-step4/cpt-step4.component.css
src/digitalIdentity-frontend/src/styles.scss

Filters in create proof template are visible now, deleted log button, minor styling adjustments
Signed-off-by: Annika Krause <annika.krause@fau.de>
RM: @steve-237

Small styling improvements concerning Create Proof Template

---

src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.html
src/digitalIdentity-frontend/src/app/pages/DI/createDI-page/createDI-page.component.spec.ts
src/digitalIdentity-frontend/src/app/pages/change-password-page/change-password-page.component.css
src/digitalIdentity-frontend/src/app/pages/change-password-page/change-password-page.component.html
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.css
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.html
src/digitalIdentity-frontend/src/app/pages/login-page/login-page.component.spec.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/forgot-password-pop-up/forgot-password-pop-up.component.css
src/digitalIdentity-frontend/src/app/shared/pop-up/forgot-password-pop-up/forgot-password-pop-up.component.html
src/digitalIdentity-frontend/src/styles.scss

The style is clean and the same everywhere now. The dark background color (which differs to the mockup) is approved by the POs.
RM: @steve-237

266 change password/login/forgot password page according to mockup

---

src/digitalIdentity-frontend/src/app/shared/filtered-table/delete-dialog/delete-dialog.component.css
src/digitalIdentity-frontend/src/app/shared/filtered-table/delete-dialog/delete-dialog.component.html
src/digitalIdentity-frontend/src/app/shared/pop-up/edit-window-pop-up/edit-window-pop-up.component.css
src/digitalIdentity-frontend/src/app/shared/pop-up/edit-window-pop-up/edit-window-pop-up.component.html
src/digitalIdentity-frontend/src/app/shared/pop-up/edit-window-pop-up/edit-window-pop-up.component.ts
src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.html

Fixing pop ups

---

src/digitalIdentity-frontend/src/app/app.component.css
src/digitalIdentity-frontend/src/app/app.component.html
src/digitalIdentity-frontend/src/app/pages/home-page/home-page.component.css
src/digitalIdentity-frontend/src/app/pages/home-page/home-page.component.html

Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

300 centered homepage icons

---

src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.ts
src/digitalIdentity-frontend/src/app/pages/change-password-page/change-password-page.component.ts

fixed rerouting bug. now stays on /password/cange if params are present

---

src/digitalIdentity-frontend/src/app/services/error-message-service/error-message.service.ts

fix double wrong email bug in forgot password

---

src/digitalIdentity-frontend/src/app/pages/credential/create-credDef/create-cred-def.component.css
src/digitalIdentity-frontend/src/app/pages/credential/create-credDef/create-cred-def.component.html

cred-def-create: added not supported to revocable

---

src/digitalIdentity-frontend/src/app/shared/filtered-table/filtered-table.component.html

fixed-indexing bug in filtered table
